# @package eval.muse.metrics.forget_ACCURACY
defaults:
  - ../../data/datasets@datasets: MUSE_forget_knowmem
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
handler: accuracy
rouge_type: rougeL_f1
batch_size: 4
datasets:
  MUSE_forget_knowmem:
    args:
      hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}
      few_shot_dataset_hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left
generation_args:
  max_new_tokens: 32
  stopwords: ["\n\n", "\nQuestion", "Question:"]
